# Generated by Django 2.2.11 on 2020-03-18 15:04

import django.db.models.deletion
from django.db import migrations, models

import cloudstorage.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('cloudstorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('all_file', cloudstorage.fields.CloudFileField(blank=True, null=True,
                                                                on_delete=django.db.models.deletion.SET_NULL,
                                                                related_name='+',
                                                                to='cloudstorage.CloudFile')),
                ('attachments', cloudstorage.fields.ManyCloudFileField(blank=True,
                                                                       related_name='example_attachments',
                                                                       to='cloudstorage.CloudFile')),
                ('image_file', cloudstorage.fields.CloudFileField(blank=True, null=True,
                                                                  on_delete=django.db.models.deletion.SET_NULL,
                                                                  to='cloudstorage.CloudFile')),
            ],
        ),
    ]
