# Generated by Django 2.2.11 on 2020-03-19 04:40

import django.db.models.deletion
from django.db import migrations, models

import drf_cloudstorage.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ('drf_cloudstorage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Example',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False,
                                        verbose_name='ID')),
                ('all_file', drf_cloudstorage.fields.CloudFileField(blank=True, null=True,
                                                                    on_delete=django.db.models.deletion.SET_NULL,
                                                                    related_name='+',
                                                                    to='drf_cloudstorage.CloudFile')),
                ('attachments', drf_cloudstorage.fields.ManyCloudFileField(blank=True,
                                                                           related_name='example_attachments',
                                                                           to='drf_cloudstorage.CloudFile')),
                ('image_file', drf_cloudstorage.fields.CloudFileField(blank=True, null=True,
                                                                      on_delete=django.db.models.deletion.SET_NULL,
                                                                      to='drf_cloudstorage.CloudFile')),
            ],
        ),
    ]
